name: Build, Test, and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 1 * *" # Runs at midnight on the 1st day of every month

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to DockerHub using PAT
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 3: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build the image for linux/amd64 platform
      - name: Build Docker image
        id: build-image
        run: |
          TAG=$(date +'%Y-%m')
          docker buildx build \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/jenkins-postman:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/jenkins-postman:$TAG \
            --output type=docker \
            .

      # Step 5: Test the image (print versions of tools)
      - name: Test Docker image
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/jenkins-postman:latest sh -c "
          echo 'Testing tools...' &&
          postman --version &&
          newman --version &&
          echo 'All tools work as expected!'
          "

      # Step 6: Push the image to DockerHub (only on push to main branch)
      - name: Push Docker image to DockerHub
        if: github.ref == 'refs/heads/main'
        run: |
          TAG=$(date +'%Y-%m')
          docker buildx build \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/jenkins-postman:latest \
            --tag ${{ secrets.DOCKER_USERNAME }}/jenkins-postman:$TAG \
            --push \
            .
